name: app_mobile
description: "AI Virtual Assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icon
  cupertino_icons: ^1.0.8
  
  # Camera & AI
  camera: ^0.10.5
  ultralytics_yolo: ^0.1.42
  tflite_flutter: ^0.12.1
  
  # Xu ly anh & File
  path_provider: ^2.1.1
  image: ^4.1.0
  
  # Mang & Tien ich
  http: ^1.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/ai_button.jpg
    - assets/classification_emotion.tflite
    - assets/model_face.tflite